main:
  - name: Skills
    url: '#features'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Academic
    url: '#academic'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 40
  - name: Impressum
    url: "/impressum"
    weight: 50
